games:
  twitch_id: int
  name: str
  box_art_url: str
commands:
  name: str
  required_role: int/str/enum?
  template: str
  cooldown: int
  game: int
  version: int
timers:
  command_name: str
  game: int
users:
  user_id: int
  role: int/str/enum?
  minutes: int
  login: str





